language: node_js
node_js:
  - "8.12.0"
before_script:
script: yarn harp compile src public
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && node_modules/.bin/surge --project public --domain porto.codes
